#!/usr/bin/env bash

declare -A RULES

_assign() {
	PAIR=($(echo $1 | sed 's/=/ /'))
	RULES[$(_strip ${PAIR[0]})]=$(_strip ${PAIR[1]})
}
_strip() {
	echo "$1" | sed 's/[\"|\(|\)|$]//ig'
}

_parseRule() {
	TYPE=$1
	shift
	declare -A PARAMS
	PARAMS[on]="--"
	PARAMS[dir]="--"
	PARAMS[proto]="--"
	PARAMS[from]="--"
	PARAMS[to]="--"
	PARAMS[target]="--"
	OLDPARAM=$1
	while (("$#")); do
		PARAM=$1
		case "$PARAM" in
			pass|block|quick)
				TYPE="$TYPE $PARAM";;
			out|in)
				PARAMS[dir]="$PARAM";;
			all)
				PARAMS[from]=any
				PARAMS[to]=any;;
			*)
				shift
				# Resolve variables
				case "$1" in
					*\$*) VALUE=${RULES[$(_strip $1)]};;
					*) VALUE=$1;;
				esac
				# Assign to param
				if [[ "$PARAM" == "->" ]]; then
					PARAM=target
				fi
				if [[ "$PARAM" == "port" ]]; then
					PARAMS[$OLDPARAM]="${PARAMS[$OLDPARAM]}:$VALUE"
				else
					PARAMS[$PARAM]=$VALUE
				fi
				OLDPARAM=$PARAM;;
		esac
		shift
	done
	echo -n "${TYPE},${PARAMS[dir]},${PARAMS[on]},${PARAMS[proto]},${PARAMS[from]},${PARAMS[to]},${PARAMS[target]}"
}

list() {
	lineNo=1
	IFS=$'\n'
	OUTPUT="NO,RULE,DIR,ON,PROTO,FROM,TO,TARGET\n"
	for LINE in $(cat /etc/pf.conf); do
		case "$LINE" in
			\#*)
				continue;;
			*=*)
				IFS=$' '
				_assign "$LINE"
				lineNo=$((lineNo - 1));;
			nat*|rdr*|scrub*)
				RINE=$(echo $LINE | tr ' ' '\t')
				IFS=$'\t'
				RULE=$(_parseRule $RINE);
				OUTPUT="${OUTPUT}${lineNo},$RULE\n";;
			*)
				echo "Unknown rule: $LINE";;
		esac
		lineNo=$((lineNo + 1))
		IFS=$'\n'
	done
	printf $OUTPUT | column -ts $','
}

add-rule() {
	# Try command before applying
	echo $@ | pfctl -nmf -
	if [ $? -eq 0 ]; then
		echo $@ >> /etc/pf.conf
		echo "Rule added"
		_silent_reload
	else
		echo "Rule is not valid, not added"
	fi
}

_silent_reload() {
	service pf reload 2>&1 > /dev/null
}
reload() {
	service pf reload
}

help() {
	echo "Usage: pfadm <command> <params>"
	echo
	echo "Available commands"
	echo "    help          Show this screen"
	echo "    list          Show all current rules"
	echo "    reload        Reload the pf daemon"
	echo "    add-rule      Adds a new rule to the list"
	echo "    remove-rule   Removes a rule from the list"
}

if [ $# = 0 ]; then help; exit 0; fi
$@